[project]
name = "plant-pics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ben Lambert", email = "blambert@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "accelerate>=1.12.0",
    "anthropic>=0.75.0",
    "boto3>=1.35.0",
    "datasets>=4.4.2",
    "pillow>=12.1.0",
    "polars>=1.36.1",
    "reverse-geocoder>=1.5.1",
    "scikit-learn>=1.8.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
    "tqdm>=4.67.1",
    "transformers>=4.57.3",
    "typer>=0.21.0",
    "vlm-toolkit>=0.1.0",
    "wandb>=0.23.1",
]

[project.scripts]
plant-filter = "plant_pics.filter:app"
plant-download = "plant_pics.download_pics:app"
plant-build-dataset = "plant_pics.build_dataset:app"

[build-system]
requires = ["uv_build>=0.9.3,<0.10.0"]
build-backend = "uv_build"
